name: Pull Request Checker

on: [pull_request]

jobs:
  Test-React:
    runs-on: ubuntu-latest
    steps:
      # Get our code into the Action ubuntu server
      - uses: actions/checkout@v3
      # Install NodeJS
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      # Install node dependencies
      - run: npm install
      # Run test suite
      - run: npm test
